# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7033ab882d4e0e7cbfffa658841a2bde5a88ed9d1015dbe3b1d56eec0cc237df9098ddbe116c4e97fa502ec62cf4e269f79f1d198ca046cb57d0feabf46cf12d

test:
  secret_key_base: dcf1ba136766ad01c60bf4d679ead3ad65a16da5574e417edae053a850c4deec101f47bad9d0706f02e193a896c2c005ba4ab28f124442640eb84f6ca90c15cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
